# Generated by Django 6.0.2 on 2026-03-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='limite_boards',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
