# Generated by Django 5.0.14 on 2026-03-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_limite_boards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='limite_boards',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
