# Generated by Django 5.0.14 on 2026-03-06 04:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0004_alter_empresa_limite_boards'),
        ('kanban', '0003_kanbanboard_compartilhado_kanbanboard_membros_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], db_index=True, default='MEDIA', max_length=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROGRESSO', 'Em Progresso'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', max_length=15)),
                ('data_vencimento', models.DateField(blank=True, db_index=True, null=True)),
                ('lembrete_em', models.DateTimeField(blank=True, null=True)),
                ('lembrete_notificado', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atribuido_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_atribuidas', to=settings.AUTH_USER_MODEL)),
                ('card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefa', to='kanban.kanbancard')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['data_vencimento', '-prioridade'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='tarefas_tar_empresa_e255b8_idx'), models.Index(fields=['empresa', 'atribuido_a', 'status'], name='tarefas_tar_empresa_d866fd_idx'), models.Index(fields=['empresa', 'prioridade'], name='tarefas_tar_empresa_ea28ce_idx'), models.Index(fields=['data_vencimento', 'status'], name='tarefas_tar_data_ve_db1179_idx'), models.Index(fields=['lembrete_em', 'lembrete_notificado'], name='tarefas_tar_lembret_f019e6_idx')],
            },
        ),
    ]
