# Generated by Django 6.0.2 on 2026-03-01 02:44

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaixaContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CANCELAMENTO', 'Cancelamento'), ('BAIXA_MANUAL', 'Baixa Manual'), ('RENEGOCIACAO', 'Renegociação')], max_length=15)),
                ('motivo', models.TextField()),
                ('data_baixa', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Baixa (CP)',
                'verbose_name_plural': 'Baixas (CP)',
                'ordering': ['-data_baixa'],
            },
        ),
        migrations.CreateModel(
            name='BaixaContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CANCELAMENTO', 'Cancelamento'), ('BAIXA_MANUAL', 'Baixa Manual'), ('INADIMPLENCIA', 'Inadimplência')], max_length=15)),
                ('motivo', models.TextField()),
                ('data_baixa', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Baixa (CR)',
                'verbose_name_plural': 'Baixas (CR)',
                'ordering': ['-data_baixa'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_nome', models.CharField(max_length=100)),
                ('agencia', models.CharField(blank=True, max_length=10)),
                ('conta', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança'), ('PI', 'Conta PIX'), ('CX', 'Caixa')], default='CC', max_length=2)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['banco_nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('numero_documento', models.CharField(blank=True, db_index=True, max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('BOL', 'Boleto'), ('CAR', 'Cartão'), ('TED', 'Transferência Bancária (TED/DOC)'), ('CHQ', 'Cheque'), ('DIN', 'Dinheiro'), ('OUT', 'Outro')], default='BOL', max_length=3)),
                ('total_parcelas', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARC_PAGA', 'Parcialmente Paga'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('BAIXA_MANUAL', 'Baixa Manual')], db_index=True, default='PENDENTE', max_length=15)),
                ('status_manual', models.BooleanField(default=False, help_text='Quando True o signal de recálculo automático é ignorado.')),
                ('data_competencia', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-data_competencia', '-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('SERVICO', 'Serviço / Pacote'), ('COMISSAO', 'Comissão')], db_index=True, default='SERVICO', max_length=10)),
                ('percentual_comissao', models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 10.00 = 10%', max_digits=5, null=True)),
                ('valor_base_comissao', models.DecimalField(blank=True, decimal_places=2, help_text='Valor da venda sobre o qual a comissão é calculada', max_digits=12, null=True)),
                ('numero_documento', models.CharField(blank=True, db_index=True, max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('BOL', 'Boleto'), ('CAR', 'Cartão'), ('TED', 'Transferência Bancária (TED/DOC)'), ('CHQ', 'Cheque'), ('DIN', 'Dinheiro'), ('OUT', 'Outro')], default='PIX', max_length=3)),
                ('total_parcelas', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARC_PAGA', 'Parcialmente Recebida'), ('RECEBIDA', 'Recebida'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('BAIXA_MANUAL', 'Baixa Manual')], db_index=True, default='PENDENTE', max_length=15)),
                ('status_manual', models.BooleanField(default=False, help_text='Quando True o signal de recálculo automático é ignorado.')),
                ('data_competencia', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['-data_competencia', '-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('serie', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Nota Fiscal (CP)',
                'verbose_name_plural': 'Notas Fiscais (CP)',
            },
        ),
        migrations.CreateModel(
            name='ParcelaContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveSmallIntegerField()),
                ('cod_barras', models.CharField(blank=True, max_length=60)),
                ('data_competencia', models.DateField(blank=True, null=True)),
                ('data_movimentacao', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(db_index=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outros_acrescimos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Parcela (CP)',
                'verbose_name_plural': 'Parcelas (CP)',
                'ordering': ['conta_pagar', 'numero_parcela'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveSmallIntegerField()),
                ('data_competencia', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(db_index=True)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outros_acrescimos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDA', 'Recebida'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Parcela (CR)',
                'verbose_name_plural': 'Parcelas (CR)',
                'ordering': ['conta_receber', 'numero_parcela'],
            },
        ),
    ]
