# Generated by Django 6.0.2 on 2026-03-01 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('empresas', '0002_initial'),
        ('financeiro', '0001_initial'),
        ('fornecedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baixacontapagar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas_contas_pagar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baixacontareceber',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas_contas_receber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_financeiras', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_bancarias', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.categoria'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='baixacontapagar',
            name='conta_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.contapagar'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='financeiro.categoria'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comissoes_pagar', to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='baixacontareceber',
            name='conta_receber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.contareceber'),
        ),
        migrations.AddField(
            model_name='notafiscalcp',
            name='conta_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='financeiro.contapagar'),
        ),
        migrations.AddField(
            model_name='parcelacontapagar',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_pagas', to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='parcelacontapagar',
            name='conta_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='financeiro.contapagar'),
        ),
        migrations.AddField(
            model_name='parcelacontareceber',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_recebidas', to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='parcelacontareceber',
            name='conta_receber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='financeiro.contareceber'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='unique_categoria_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['empresa', 'status'], name='financeiro__empresa_cd80b6_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['empresa', 'fornecedor'], name='financeiro__empresa_14a32f_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['empresa', 'status'], name='financeiro__empresa_4c7022_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['empresa', 'tipo'], name='financeiro__empresa_dc8f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['empresa', 'cliente'], name='financeiro__empresa_ffae49_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['empresa', 'fornecedor'], name='financeiro__empresa_c9ca1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='notafiscalcp',
            constraint=models.UniqueConstraint(fields=('conta_pagar', 'numero', 'serie'), name='unique_nf_por_conta_pagar'),
        ),
        migrations.AddConstraint(
            model_name='parcelacontapagar',
            constraint=models.UniqueConstraint(fields=('conta_pagar', 'numero_parcela'), name='unique_numero_parcela_por_conta'),
        ),
        migrations.AddConstraint(
            model_name='parcelacontareceber',
            constraint=models.UniqueConstraint(fields=('conta_receber', 'numero_parcela'), name='unique_numero_parcela_por_conta_receber'),
        ),
    ]
