# Generated by Django 5.0.14 on 2026-03-07 04:08

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('empresas', '0004_alter_empresa_limite_boards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('TAREFA_ATRIBUIDA', 'Tarefa Atribuída'), ('TAREFA_CONCLUIDA', 'Tarefa Concluída'), ('TAREFA_VENCIMENTO', 'Vencimento de Tarefa'), ('TAREFA_LEMBRETE', 'Lembrete de Tarefa'), ('TAREFA_REAGENDADA', 'Tarefa Reagendada'), ('KANBAN_CARD_MOVIDO', 'Card Movido')], db_index=True, max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('WEB', 'Web (WebSocket)'), ('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram')], default='WEB', max_length=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('FALHOU', 'Falhou')], db_index=True, default='PENDENTE', max_length=10)),
                ('lida', models.BooleanField(db_index=True, default=False)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='core.notificacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destinatário de Notificação',
                'verbose_name_plural': 'Destinatários de Notificações',
                'ordering': ['-notificacao__data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIADO', 'Criado'), ('EDITADO', 'Editado'), ('INATIVADO', 'Inativado'), ('ATIVADO', 'Ativado'), ('MOVIDO', 'Movido'), ('REORDENADO', 'Reordenado'), ('REMOVIDO', 'Removido'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('BAIXA', 'Baixa'), ('CANCELAMENTO', 'Cancelamento'), ('PAGAMENTO', 'Pagamento')], max_length=20)),
                ('modulo', models.CharField(max_length=30)),
                ('objeto_tipo', models.CharField(max_length=50)),
                ('objeto_id', models.PositiveIntegerField()),
                ('objeto_repr', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='empresas.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['empresa', '-data'], name='core_auditl_empresa_534436_idx'), models.Index(fields=['modulo', 'objeto_tipo', 'objeto_id'], name='core_auditl_modulo_7ad487_idx'), models.Index(fields=['usuario', '-data'], name='core_auditl_usuario_ea82ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to=apps.core.models._documento_upload_path)),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('tamanho', models.PositiveIntegerField(default=0, help_text='Tamanho em bytes')),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['empresa', '-data_criacao'], name='core_docume_empresa_a5d214_idx'), models.Index(fields=['content_type', 'object_id'], name='core_docume_content_ac0128_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['empresa', '-data_criacao'], name='core_notifi_empresa_89bc90_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['content_type', 'object_id'], name='core_notifi_content_6f40ad_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['tipo', 'data_criacao'], name='core_notifi_tipo_edd543_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaodestinatario',
            index=models.Index(fields=['usuario', 'lida'], name='core_notifi_usuario_31053b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaodestinatario',
            index=models.Index(fields=['usuario', 'status'], name='core_notifi_usuario_0f36dc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaodestinatario',
            index=models.Index(fields=['status', 'canal'], name='core_notifi_status_e61716_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaodestinatario',
            index=models.Index(fields=['notificacao', 'usuario'], name='core_notifi_notific_b6d1e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificacaodestinatario',
            constraint=models.UniqueConstraint(fields=('notificacao', 'usuario', 'canal'), name='unique_destinatario_por_canal'),
        ),
    ]
