# Generated by Django 6.0.2 on 2026-03-01 02:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=14)),
                ('ie', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=11)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Informe DDD + número sem formatação.')])),
                ('telefone_secundario', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Informe DDD + número sem formatação.')])),
                ('site', models.URLField(blank=True)),
                ('cep', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'CEP deve conter 8 dígitos.')])),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('pais', models.CharField(default='BR', max_length=2)),
                ('banco_nome', models.CharField(blank=True, max_length=100)),
                ('banco_agencia', models.CharField(blank=True, max_length=10)),
                ('banco_conta', models.CharField(blank=True, max_length=20)),
                ('banco_pix', models.CharField(blank=True, max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['razao_social'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cnpj__gt', '')), fields=('empresa', 'cnpj'), name='unique_fornecedor_cnpj_por_empresa'), models.UniqueConstraint(condition=models.Q(('cpf__gt', '')), fields=('empresa', 'cpf'), name='unique_fornecedor_cpf_por_empresa')],
            },
        ),
    ]
