# Generated by Django 5.0.14 on 2026-03-01 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancoluna',
            name='cor',
            field=models.CharField(default='#5dca6c', max_length=7),
        ),
        migrations.CreateModel(
            name='KanbanColunaAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALTERAR_STATUS_TAREFA', 'Alterar status da tarefa'), ('ALTERAR_PRIORIDADE', 'Alterar prioridade'), ('NOTIFICAR_RESPONSAVEL', 'Notificar responsável'), ('NOTIFICAR_EMPRESA', 'Notificar toda a empresa')], max_length=30)),
                ('parametro', models.CharField(blank=True, max_length=50)),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='kanban.kanbancoluna')),
            ],
            options={
                'verbose_name': 'Ação de Coluna',
                'verbose_name_plural': 'Ações de Coluna',
            },
        ),
        migrations.AddConstraint(
            model_name='kanbancolunaacao',
            constraint=models.UniqueConstraint(fields=('coluna', 'tipo'), name='unique_acao_por_coluna'),
        ),
    ]
