# Generated by Django 5.0.14 on 2026-03-06 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_empresa_limite_boards'),
        ('kanban', '0002_alter_kanbancoluna_cor_kanbancolunaacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanboard',
            name='compartilhado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kanbanboard',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='boards_acesso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_cards', to='empresas.empresa'),
        ),
    ]
