# Generated by Django 5.0.14 on 2026-03-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_kanbanboard_compartilhado_kanbanboard_membros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='lembrete_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
