# Generated by Django 6.0.2 on 2026-03-01 04:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=2)),
                ('passaporte', models.CharField(blank=True, max_length=20)),
                ('passaporte_emissao', models.DateField(blank=True, null=True)),
                ('passaporte_expiracao', models.DateField(blank=True, null=True)),
                ('passaporte_pais', models.CharField(blank=True, max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rede_social', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ClienteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cpf', 'CPF'), ('rg', 'RG'), ('cnh', 'CNH'), ('outro', 'Outro')], max_length=20)),
                ('tipo_outro', models.CharField(blank=True, max_length=50)),
                ('numero', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='ClienteTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proprio', 'Próprio'), ('outro', 'Outro')], default='proprio', max_length=20)),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('numero', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
    ]
